spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PASSOWRD}

oauth:
  github:
    redirect_uri: ${OAUTH_REDIRECT_URI}
    client_id: ${OAUTH_CLIENT_ID}
    client_secret: ${OAUTH_CLIENT_SECRET}
    scope: ${OAUTH_SCOPE}

jwt:
  token:
    secret_key: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}
